Update to client.pp
This is a fix for
Error: Error while evaluating a Resource Statement, Evaluation Error: Illegal Class name in class reference. A TypeReference['Voms::Install']-Type cannot be used where a String is expected.

Tested with Puppet 5.5.